# Generated by Django 5.0.7 on 2024-08-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='password',
            field=models.CharField(default=123234, max_length=30),
            preserve_default=False,
        ),
    ]
